export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST : 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS : 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:"GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST:' ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:' ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:' ADD_NEW_CATEGORY_FAILURE'
}

export const productConstants= {
    GET_PRODUCTS_BY_SLUG:'GET_PRODUCTS_BY_SLUG',
    GET_ALL_PRODUCTS_REQUEST : 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS : 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE : 'GET_ALL_PRODUCTS_FAILURE' ,

    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
}


export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST : 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS : 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE : 'GET_ALL_INITIAL_DATA_FAILURE'
}

export const cartConstants = {
    ADD_TO_CART: 'ADD_TO_CART'
}